name: openproject-mcp-oauth

services:
  # The actual OpenProject MCP Server (internal, not exposed)
  openproject-mcp-server:
    build: https://github.com/firsthalfhero/openproject-mcp-server.git
    container_name: openproject-mcp-server
    environment:
      # === OpenProject Connection Settings ===
      - OPENPROJECT_URL=${OPENPROJECT_URL}
      - OPENPROJECT_API_KEY=${OPENPROJECT_API_KEY}
      
      # === MCP Server Settings (Internal) ===
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8081
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
      - OPENPROJECT_CACHE_TIMEOUT_MINUTES=${CACHE_TIMEOUT:-5}
      - OPENPROJECT_PAGINATION_SIZE=${PAGINATION_SIZE:-100}
      - OPENPROJECT_MAX_RETRIES=${MAX_RETRIES:-3}
    volumes:
      - ${DATA_PATH:-./data}/mcp-logs:/app/logs
      - ${DATA_PATH:-./data}/mcp-data:/app/data
    networks:
      - mcp-network
    restart: unless-stopped
    expose:
      - "8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  # OAuth Wrapper (protects the MCP server with MCP OAuth spec)
  oauth-wrapper:
    build:
      context: .
      dockerfile: Dockerfile.oauth
    container_name: oauth-wrapper
    environment:
      # === OAuth Configuration for Claude ===
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      
      # === Public URL Settings ===
      - BASE_URL=${BASE_URL}
      
      # === Internal MCP Server URL ===
      - MCP_SERVER_URL=http://openproject-mcp-server:8081
    volumes:
      - ${DATA_PATH:-./data}/oauth-data:/app/data
    networks:
      - mcp-network
    restart: unless-stopped
    depends_on:
      openproject-mcp-server:
        condition: service_healthy
    expose:
      - "8080"

  
  # Pangolin Newt Tunnel (exposes oauth-wrapper to the internet)
  mcp-oauth-newt:
    image: fosrl/newt
    container_name: mcp-oauth-newt
    restart: always
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
    networks:
      - mcp-network
    depends_on:
      - oauth-wrapper

networks:
  mcp-network:
    driver: bridge
